server:
  port: 20888


hehe:
  name: 123456
  psw: 999999
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/info?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    max-active: 20
    max-idle: 8
    min-idle: 8
    initial-size: 10

logging:
  config: classpath:log4j2.xml

#配置分页插件pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql